framework:
  asset_mapper:
    # The paths to make available to the asset mapper.
    paths:
      - "%kernel.project_dir%/assets"
      - "%kernel.project_dir%/vendor/twbs/bootstrap/scss"
      - "%kernel.project_dir%/vendor/twbs/bootstrap/dist/js"
    missing_import_mode: strict

when@prod:
  framework:
    asset_mapper:
      missing_import_mode: warn
